# Checksout code in the git repo
#ssh-keyscan $YOUR_GIT_HOST > /tmp/known_hosts # git this from ~/.ssh/knownhost
#https://github.com/kubernetes/git-sync/blob/master/docs/ssh.md
# Remove git
apiVersion: v1
kind: Pod
metadata:
  name: git-sync1
spec:
  containers:
      - name: git-sync1
        image: k8s.gcr.io/git-sync:v3.1.5
        args:
         - "-ssh"
         - "-repo=git@github.com:bandeep2000/samples1"
         - "-dest=linux"
         - "-branch=master"
         - "-depth=1"
        securityContext:
          runAsUser: 65533 # git-sync user
        volumeMounts:  # secret volume mount
        - name: git-secret
          mountPath: /etc/git-secret
          readOnly: true
        - name: git-source
          mountPath: /tmp/git
      - name: python
        image: python:2.7
        command: ["sleep","3600"]
        volumeMounts:
        - name: git-source
          mountPath: /tmp/git1
  securityContext:
        fsGroup: 65533 # to make SSH k
  volumes:
      - name: git-secret
        secret:
          secretName: git-creds
          defaultMode: 0400
      - name: git-source
        emptyDir: {}