apiVersion: v1
kind: Pod
metadata:
  name: git-test1
spec:
  initContainers:
  - image: k8s.gcr.io/git-sync:v3.0.1
    name: test-server
    volumeMounts:
    - name: git-source
      mountPath: /tmp/git
    env:
    - name: GIT_SYNC_REPO
      value: https://github.com/bandeep2000/samples1.git  ##Changing value
    - name: GIT_SYNC_DEST
      value: git-sync
    - name: GIT_SYNC_USERNAME
      value: bandeep2000
    - name: GIT_SYNC_ONE_TIME  
      value: "true"
    - name: GIT_SYNC_PASSWORD
      valueFrom:
          secretKeyRef:
            name: git-secret
            key:  password
  containers:
  - image: debian
    name: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: git-source
      mountPath: /tmp/git1
  volumes:
  - name: git-source
    emptyDir: {}
